### ISSUE TITLE
Allow a user to set the date to last day of the month

### ISSUE THREAD

**Issue by NPadrutt** [MoneyFox/MoneyFox#2039] opened 2021-04-29 09:38 UTC
**Is your feature request related to a problem? Please describe.**
I have a payment that is always executed on the last day of the month. Currently I would 

**Describe the solution you'd like**
Checkbox in the payment for "Last day of the month" which during generating the payment sets it to the last day.

**Comment by kg8z** [comment] 2022-03-03 05:32
@NPadrutt  - Just to confirm, is the enhancement intended to add a checkbox next to the date for a regular (one-time) payment or add a new option to the Recurrence list for recurring payments (or both)? Either way, I'll grab this one if you want to assign it to me.

**Comment by NPadrutt** [comment] 2022-03-03 16:03
Also, currently the calculation if a payment is up for a new recurrence is bot so nice. So if you have a cool idea to refactor that, feel free to take a look at that as well.

**Comment by kg8z** [comment] 2022-03-04 02:42
@NPadrutt - Sounds good. The end of month functionality seems fairly straightforward. I'll give some thought to the recurrence calculation and see if I can find a better approach.

**Comment by NPadrutt** [comment] 2022-03-04 10:14
@kg8z  yeah it should be rather straight forward.

As a thought I had regarding the calculation of the recurrence. Right now, there is a service that determines whether a recurring payment is up for renewal. But wouldn't it be the responsibility of the recurring payment itself to know when it must be repeated? If so, then mabye the logic of that service should go to the RecurringPayment directly.

**Comment by kg8z** [comment] 2022-03-05 02:21
@NPadrutt - Embedding the logic to create a transaction and increment the recurrence date into the RecurringPayment class itself makes a lot of sense. We'd still need something to trigger the logic within each recurring payment instance (startup check or perhaps a timer) but that could be a simple scheduler. I do like the idea of compartmentalizing the logic within the Model, though. I'll try some things out. Thanks!

**Comment by NPadrutt** [comment] 2022-03-05 09:20
Currently that is triggered on startup, which I think is fine. On windows I used to use Background jobs. But that was quite a lot of work for basically not too much value generated. Especially since those used to run in a separate process. So you would have to synchronise those back to the main thread ^^

**Comment by kg8z** [comment] 2022-03-07 02:35
That makes sense. What about the mobile apps? I'm new to mobile development so forgive the newbie question. It seems like mobile apps run in the background pretty much perpetually. Does "startup" on a mobile app fire each time it's made active or only when it's run when not already in the background?

**Comment by NPadrutt** [comment] 2022-03-08 06:58
ah, exactly. On mobile it's on launch or being reactivated. So when you switch to another app and back the startup tasks are executed.

**Comment by kg8z** [comment] 2022-04-02 22:03
@NPadrutt  - Is there a reason that the recurrence calculations for Quarterly and Biannually use days (93 and 184 respectively) rather than months? It seems like a more precise approach would be to use months (3 and 6 respectively). For example, to check Quarterly, something like this:
DateTime.Today.AddMonths(-3) >= lastRecurrenceCreated.Date 

instead of 

DateTime.Now - lastRecurrenceCreated.Date >= 93

I can update the logic but wanted to make sure there wasn't a specific reason for using days before doing so.

**Comment by NPadrutt** [comment] 2022-04-03 12:04
@kg8z  good question. To be honest, I'm not sure if that was since there was no method for weeks so I used days for everything. But I would say definitely change that to months :)

**Comment by kg8z** [comment] 2022-04-04 01:30
@NPadrutt  - The current logic to trigger payment creation for recurring payments will miss transactions if the application hasn't been run within 2 cycles of the recurrence period (e.g. weekly, last run >14 days ago). Consider the following scenario...

There is a recurring payment created for a weekly Friday paycheck where the last recurrence creation date was March 18, 2022.  Today is April 3, 2022 and the person runs the MoneyFox application for the first time since returning from holiday. Two Fridays have passed while the person was on holiday (March 25 and April 1). The current behavior of the application creates a single payment transaction for today's date, April 3, 2022, which not only breaks the weekly cadence but also changes the day of week of the series.

It seems to me that the recurrence date calculation should be based on the start date of the recurring payment object and all instances of recurrence should be generated if the user hasn't run the application in a while. In the aforementioned scenario, I would expect the March 25 and April 1 payment transactions to be created automatically, keeping to the Friday weekly cadence. This would have happened if I ran the app regularly, but not if there was a gap. Basically, I would expect the same transactions to be created whether I run the app daily or leave it for a period of time (which is not the case currently).

This is a very significant change to the current logic so I would love your thoughts.  Thanks.

**Comment by NPadrutt** [comment] 2022-04-04 15:41
yeah that is a good point. I think originally that was designed with UWP background tasks and those where configured to run every like 8 hours so that scenario could not happen. But with android and especially iOS that doesn't work. So yeah I agree with you, that the app should generate all recurrences. But I would move that to a separate issue, since from what I understand, this issue here is not directly affected by that as far as I understand.

**Comment by kg8z** [comment] 2022-04-05 03:31
@NPadrutt - Apologies in advance for this very long comment to explain the situation more clearly...

Sorry, I went too broad in my explanation of the behavior and didn't tie it back to this specific enhancement. I discovered the aforementioned behavior as I was modifying the logic that triggers new recurring payment transactions. The way in which the payment date is calculated for the new payment transaction is as follows:

Monthly Recurrence - {Current Year} / {Current Month} / {Day of Month from Payment Start Date}
Everything Else - {Today}

The behavior for Daily, DailyWithoutWeekend, Weekly, and Biweekly can be unexpected if the app isn't run daily, but this isn't relevant to this enhancement. I do think it should be fixed but, as you say, that could happen via another issue.

The behavior for Monthly is a bit unexpected as this is the only recurrence type that will trigger a payment transaction in the future. For example, I created a monthly recurring payment with a date of March 10, 2022. When I reran the application today (April 4) it automatically created a payment transaction with a future date of April 10, 2022.  This may be OK (though it seems like the transaction should be created on the 10th rather than the first day that the application is run in April), but none of the other recurrence types create future-dated transactions so it feels inconsistent.

The behavior for Quarterly and Biannually is calculated based on days rather than months (which we discussed in earlier comments). I can simply make the triggering logic for these behave consistently with Monthly which again would be fine for this enhancement. It would alter existing behavior, but we're already introducing changes from days-based to months-based calculations so that should be fine (I think).

The behavior for Bimonthly and Yearly is where things get interesting relative to this enhancement. For both of them, the new payment transaction is always created with current date. Because the recurrence triggering logic only considers the month & year in the check it automatically creates a new payment transaction on the first day of the month when the application is run. For example, a bimonthly recurring payment with a date of February 28 will create the next payment transaction instance on April 1 (or whichever date in April the application is first run).

So... There are really two fundamental issues at hand. What do you think about the following approach:
1. Recurrence gaps if app isn't run for a long period of time - Something we should fix, but not directly relevant to this enhancement. Create a separate issue for this.
2. Day of week/month not retained for Weekly/Biweekly/Monthly/Bimonthly/Quarterly/Biannually/Yearly recurring payments - As part of this issue, alter existing behavior so Weekly/Biweekly transactions retain the day of week (e.g. Fridays) and the others retain the day of month (e.g. the 6th). I'll then add the "Last Day of Month" functionality on top of this.

Again, sorry this was so verbose. Hopefully it all makes sense. Let me know your thoughts on the proposed approach.

**Comment by NPadrutt** [comment] 2022-04-05 19:42
Hey @kg8z 

You make a good point and I agree with the fundamental issues and your approach makes sense to me.

I don't quite understand this calculation: 
```
Monthly Recurrence - {Current Year} / {Current Month} / {Day of Month from Payment Start Date}
Everything Else - {Today}
```
Can you elaborate on that a bit?

You are right that it is inconsistent with how recurrences are triggered when you compare weekly to monthly. The monthly recurrence is with the one of monthly payments in mind. So, if you have for example your rent that is paid every month on the 25th you already want to have that in your end of month balance by the first day of the month.

There could be a change where we always generate one recurrence ahead. so basically, when I have a recurring payment that occurs weekly and it's due today, then the next recurrence for the 12.04. is generated now.
But still, I agree with you that the monthly, bimonthly, quarterly, yearly and biyearly should be oriented on the date and the weekly and biweekly should be oriented on the day of the week.

**Comment by kg8z** [comment] 2022-04-06 04:06
@NPadrutt  - Thanks for the feedback and explaining the reason for the future dating. This makes sense. I'll proceed with altering the logic so weekly transactions continue to use the current date and monthly/bimonthly/quarterly/etc. will be tied to a day of month. This also helps me move forward with the new "last day of month" functionality.

The calculation I mentioned was intended to describe how the method RecurringPaymentHelper.GetPaymentDateFromRecurring determines the date that's used on the new transaction. Monthly recurrence has special logic, everything else (including bimonthly, quarterly, biannually, and annually) uses DateTime.Today. You can ignore this as I'm going to adjust the logic anyway. I included it to highlight the inconsistent behavior but I think we're on the same page. Thanks again.

**Comment by NPadrutt** [comment] 2022-04-09 15:50
@kg8z 
I did a rather big change with a lot of formatting changes to have that nicer and consistent. I think it would make sense you pull the changes sooner rather than late to have not too many merge conflicts. Sorry for any inconveniences!

**Comment by kg8z** [comment] 2022-04-11 03:14
@NPadrutt  - Thanks for the heads-up. I'll pull them into my fork/branch. Cheers.

**Comment by kg8z** [comment] 2022-04-13 02:15
@NPadrutt - Thanks again for letting me know about the formatting changes. They've all been merged into my branch. I'm glad you mentioned it now so I could address the conflicts before they got too big. :-)

**Comment by NPadrutt** [comment] 2022-04-13 08:07
@kg8z  nice, glad to hear! I hoped that I don't mess too much with what changes you already made. :)

**Comment by kg8z** [comment] 2022-04-14 23:48
Not at all. I like the new pattern of including the parameter names in method calls. Much clearer.

**Comment by kg8z** [comment] 2022-04-16 04:08
@NPadrutt  - I just noticed that the MoneyFox.SharedKernel project shows as "(not found)" when I open the MoneyFox.WinUI Solution. Assuming this was part of the recent clean-up effort you performed and the Solution just needs to have the project removed. Everything compiles and runs so it's not a problem, just letting you know.
<img width="264" alt="image" src="https://user-images.githubusercontent.com/81488531/163660776-32e54eee-a6cf-4956-87b2-b10af874c044.png">

**Comment by NPadrutt** [comment] 2022-04-16 10:55
@kg8z thanks for letting me know. You are right, that was from there. It seems I have missed that solution. I'll submit a change for that.

**Comment by kg8z** [comment] 2022-04-18 00:41
@NPadrutt - Did you change the default encoding in your VS.Net environment to UTF-8? I started getting warnings about encoding mismatches (mine being Western/Windows; latest from Github being UTF-8) after I pulled the latest changes. I tried to prevent code diffs due to encoding differences when I pushed my changes. Hopefully, it worked. Let me know if I should change my environment config. I'm on VS.Net 2022 Community Edition.

**Comment by NPadrutt** [comment] 2022-04-19 06:34
@kg8z yeah I did set that in the editconfig to have that basically centralized at one place. I'll keep an eye out if that causes issues.

**Comment by NPadrutt** [comment] 2022-04-24 19:17
@kg8z  I think we can close this, right?

**Comment by kg8z** [comment] 2022-04-25 01:24
@NPadrutt - Yep. This one’s done. Thanks.

**Closed** 2022-04-25 07:36 UTC
Labels: enhancement, android, windows, iOS
