### ISSUE TITLE
Eternal loading after "Name already used" message on creating account

### ISSUE THREAD

**Issue by sgermosen** [MoneyFox/MoneyFox#2064] opened 2021-08-24 22:44 UTC
**Describe the bug**

Eternal loading after "Name already used" message on creating account

**To Reproduce**
1. Go Create account
2. Create an account like "test account"
3. Create a new account
4. Use the same name previously used

**Expected behavior**
Need to display the message and wait a clic on ok button or go to list of accounts after the message.

**Screenshots**

![Screenshot_2021-08-24-18-33-12-163_com applysolutions moneyfox](https://user-images.githubusercontent.com/23745678/130699547-0b81b1b3-4902-4a31-ae84-560432bb0942.jpg)
![Screenshot_2021-08-24-18-33-47-070_com applysolutions moneyfox](https://user-images.githubusercontent.com/23745678/130699566-18c00308-d2d2-48e0-85c1-32022eae8f79.jpg)
![Screenshot_2021-08-24-18-33-52-711_com applysolutions moneyfox](https://user-images.githubusercontent.com/23745678/130699580-9cbf741e-5e31-4177-8e84-382e9ebee58f.jpg)
![Screenshot_2021-08-24-18-33-56-632_com applysolutions moneyfox](https://user-images.githubusercontent.com/23745678/130699589-792958ee-55f9-4078-928a-bfea9232be5f.jpg)

**Smartphone (please complete the following information):**
 - Device: Xiaomi X3
 - OS: Android
 - Version: 10

**Additional context**
If I delete an account, the name of that account can't be used, so, delete is not deleting properly

**Comment by NPadrutt** [comment] 2021-08-25 06:32
Hi @sgermosen 
Thanks for reporting! Seems we have a coordination issue here.

To your additional context: when you delete an account it is currently only marked as deleted but not "physically" removed from the table. Therefore the name is not released with that. The idea being, that you could restore a deleted account.

**Comment by kg8z** [comment] 2022-02-19 05:52
@NPadrutt - I believe there are 2 things at play here:

First - As you mentioned, trying to create a new account with the same name as an existing account is supposed to show an error dialog with the text "An Account with that name already exists." However, the call `await dialog.ShowAsync();` is throwing an exception which causes the app to hang with a spinning wheel and a window stating "Saving Account..." I'm able to reproduce this whether the naming conflict is with a deleted or active account. I believe this is happening because only one ContentDialog window can be open at a time and the active window (AddAccountDialog) is a ContentDialog trying to open another ContentDialog (the error message). I'm giving some thought to how this can be fixed but curious if you have ideas. This seems like a bug that should be fixed.

Second - New accounts can't be created using the same name as an account that's been deleted because records aren't deleted, they're Deactivated. Your rationale to do this to allow for restoring accounts in the future makes sense. However, it does seem like there should be a way to reuse names of Deactivated accounts. One thought would be to add a suffix to the name when an account is Deactivated to make it distinct. Something like {Account Name} (Archived: {Account ID}); for example "Checking (Archived: 3)". It's not elegant but it would allow the same name to be created and deleted at will without conflict. This seems more like an enhancement to me.

I'm happy to work on this if you want to assign the issue to me.

**Comment by NPadrutt** [comment] 2022-02-19 12:05
@kg8z thanks for your analysis. On Android and iOS / Xamarin Forms the issue with the dialogs shouldn't be present right? I thought that is only on WinUI / UWP. 
But in any case if there are multiple dialogs on windows we should fix that since that definitely will cause an issue. Question then is if we handle the exception from the duplicated name wrong in the viewmodel? 

I was actually deliberating in general with the account name to just allow using the same name multiple times. My initial intention was to help users preventing accidental wrong inputs. But in the end, I'm not sure in that case if the cure is worse than the illness.
Thoughts?

Happy to assign you to this. Let me know if you need inputs.

**Comment by kg8z** [comment] 2022-02-20 19:24
@NPadrutt  - Good question. I only tried to reproduce on Windows so not sure about iOS/Android. However, the @sgermosen screenshots look fairly consistent with the behavior I saw in Windows so it seems like the problem at least exists on Android. I've not done any mobile development in Visual Studio yet so not sure if there are built-in emulators that I can use to debug or if I need a device. I'll poke around.

As for your comment about the merits of requiring unique account names... Since the name is the only attribute visible to the end-user it does seem like requiring it be unique makes sense. If there was additional information in the account record (e.g. account number, financial institution, account type, etc.), I could see allowing reuse of account names since the combination of these additional fields could be used to distinguish between accounts with the same name.

With all of that said, here are my thoughts... I would allow for duplicate account names **but** display a warning with a Yes/No "Do you want to continue" if the new account has the same name as an existing **active** account (no warning if the conflict is with a Deactivated account). This would inform the end-user of the potential accidental input and allow them to make a conscious decision. If you agree with that logic, we still have the dialog problem since the warning will throw the same exception we're having with the error.

Let me know if you just want me to fix the exception with the error dialog or if you agree with my thoughts and want me to adjust the logic to allow for duplicates and display a warning (and still fix the dialog issue).

**Comment by NPadrutt** [comment] 2022-02-20 19:32
I like your suggestion!
Instead of using a dialog for the warning you could make a hint under the name textbox and display a message there. I think that would be nice from a UX perspective and soll the dialog problem to a degree as well.

**Comment by NPadrutt** [comment] 2022-02-20 19:36
@kg8z  forgot the mention, and it seems you can't add that afterwards anymore ^^

**Comment by kg8z** [comment] 2022-02-25 05:24
@NPadrutt  - This got quite a bit more complex when I started digging in. To answer your question about Xamarin forms, the conflict between an open ContentDialog (account and category add/update forms) and error messages doesn't exist but the problem described by @sgermosen is caused by a conflict between the "Loading..." dialog box and an attempt to then open an error dialog. I should be submitting a PR shortly with the following functionality changes:

Bug Fixes
- Win: Removed "Loading..." dialog calls when saving Account and Category modifications because this simply won't work.
- Win: Account and Category modification pages are now hidden before displaying error messages, then restored after the error is acknowledged. Not super elegant, but this is the best I could do without overhauling messaging or refactoring the pages so they aren't dialogs.
- Mobile: Close the "Loading..." dialog as part of the DialogService routines that display error messages, allowing the error dialogs to open and mitigate the initial issue that was reported.
- Win/Mobile: Set loadingDialog=null in DialogService.HideLoadingDialogAsync routine so subsequent null checks behave properly.

Enhancements
- Win/Mobile: Updated duplicate account name check to exclude Deactivated accounts as well as the current account (for update operations).
- Win/Mobile: When duplicate account names are found, the user is given the option to proceed with allowing the duplicate (both new accounts and renaming existing accounts).
- Win/Mobile: Added logic during account name updates to only perform duplicate checks if the name was changed.

There were also a few other housekeeping items where I pushed code down to base classes for simplicity.

A few items to note:
- I was able to get the Android emulator working and test my changes on Android. I haven't figured out how to get iOS working so I was unable to test on iOS. My changed **shouldn't** differ between mobile platforms, but certainly worth validating.
- The enhancement to prompt the user to continue with duplicate names requires an update to the Strings resource named "DuplicateAccountMessage". I changed the English resource to "An Account with that name already exists. Continue with saving?" I'll do my best to update the other languages but could use help with translations.

Sorry if this message is too verbose but I thought it was worth sharing given the magnitude of changes relative to the original problem report.

Let me know if you have any comments, questions, or concerns. I'll submit a PR sometime in the next couple of days.

**Comment by NPadrutt** [comment] 2022-02-25 19:53
Hey @kg8z 

Thanks for the update. Quite the work you did here! For me everything you state sounds logical. So I'm looking forwards to review the PR.

Regarding the iOS version: to debug that you actually need a Mac. Sorry, I should have told you that earlier. I hope you didn't spend too much time trying to get that working.
As you already stated the platform independant code shouldn't be a problem anyway. And I usually dogfood it with the test flight on my phone for a while before releasing.

For the translation I would suggest you just add a new localization to the default dictionary (the english one). The translation itself is done via [Crowdin](https://crowdin.com/project/money-fox). As soon as the PR is merged it automatically updates it and the missing translation do show up. German I updated myself. With the rest we are unfortunately reliant on community contributions.

**Comment by NPadrutt** [comment] 2022-02-27 12:45
Fixed. Thanks @kg8z

**Closed by NPadrutt** 2022-02-27 12:45 UTC
Labels: bug

**Comment by NPadrutt** [comment] 2022-02-27 13:34
@kg8z if you have a Mac you can install vs for mac there. With that you get the mac agent. Then you can connect with your vs on windows to that agent and basically deploy via that and stream the simulator back to your windows machine.

**Comment by kg8z** [comment] 2022-02-27 20:40
@NPadrutt  - Great tip. I'll give that a try. Thanks!
