### ISSUE TITLE
Change default target account to the one of the previous page

### ISSUE THREAD

**Issue by cloudstalker** [MoneyFox/MoneyFox#1365] opened 2018-06-14 10:58 UTC
So when there are several accounts, when I click open the accounts other than the first and hit the "add income/expense" button, the preset target account in the opened dialog is the first account. Might be better if we change it to the account whose page we hit the add button from. Same thing for transfer I guess.

**Comment by NPadrutt** [comment] 2018-06-14 12:36
Definitly. There is already an issue for this. See here #1141

**Comment by cloudstalker** [comment] 2018-06-14 12:45
lol sorry about duplicating

**Comment by NPadrutt** [comment] 2019-12-20 13:52
closed since duplicate of #1141

**Closed by NPadrutt** 2019-12-20 13:52 UTC
Labels: duplicate, enhancement
