### ISSUE TITLE
In Windows updating category causes all categories to change

### ISSUE THREAD

**Issue by MatthewJamesHill** [MoneyFox/MoneyFox#1038] opened 2016-08-31 08:34 UTC
Adding an income / expense / transfer with a category changes the category of all existing incomes / expenses / transfers to match the most recently used category. Same issue with updating an income / expense / transfer

**Comment by NPadrutt** [comment] 2016-08-31 10:19
is that on windows  or android ?

**Comment by MatthewJamesHill** [comment] 2016-08-31 10:51
Windows, but I've not tried Android yet so it may be there too

**Comment by NPadrutt** [comment] 2016-08-31 12:04
mh, couldn't reproduce this so far.. still trying on both platforms..

**Comment by MatthewJamesHill** [comment] 2016-08-31 13:45
Ah, sorry. Had a little more of a play around, it seems to only happen when you change category then click cancel. Saving will update the selected item only.

**Comment by NPadrutt** [comment] 2016-08-31 14:00
ah, yes. and after a restart the old category is displayed again. the issue is that we bind the the properties directly to the item and after the cancel it doesn't get reloaded from the cache or the database.

**Comment by MatthewJamesHill** [comment] 2016-08-31 14:26
Sounds similar to the problem I had in updating issue #432 

Perhaps updating cancel so that when the previous view is returned to it reloads the cache or database?

**Comment by NPadrutt** [comment] 2016-08-31 14:41
that should work. At least after the change of #1034

**Comment by NPadrutt** [comment] 2016-09-12 15:14
Can you still reproduce this issue with  the PR above ?

**Comment by MatthewJamesHill** [comment] 2016-09-12 19:21
I've fetched your changes and am still getting the same problem. Now it also changes all categories when you cancel OR save. But still is only a binding issue as reloading the app removes all changes.

**Comment by NPadrutt** [comment] 2016-10-25 15:34
there where some bigger changes and since then I can't see this happen again. @MatthewJamesHill  do you still have this issue in the current master?

**Comment by NPadrutt** [comment] 2016-11-02 10:56
Close this since I couldn't reproduce it. Please reopen if it happens again on the current master.

**Closed by NPadrutt** 2016-11-02 10:56 UTC
Labels: bug
