### ISSUE TITLE
Changing target account when editing transfer causes balances to not be updated

### ISSUE THREAD

**Issue by kerbowa** [MoneyFox/MoneyFox#971] opened 2016-07-03 19:32 UTC
It also caused a negative balance in a test account to add to the total amount instead of subtract.

**Comment by wobrek** [comment] 2016-07-03 20:32
#972

**Comment by NPadrutt** [comment] 2016-10-25 15:23
This is related to #972

**Comment by kg8z** [comment] 2022-02-26 02:17
@NPadrutt - Is this still an issue? I tried several permutations of updating transfers and was unable to reproduce.

**Comment by NPadrutt** [comment] 2022-02-26 09:54
It might well be that your fix for the transfers did fix this too. So I'm closing this for now. Otherwise we can reopen.

**Closed by NPadrutt** 2022-02-26 09:54 UTC
Labels: bug
